server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/films
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
    schemas: public
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  file:
    path: ./logs